name: geo-dash-rl
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.16=py311h50f4ffc_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h982b769_0
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.8.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - krb5=1.21.3=h237132a_0
  - libcxx=20.1.8=hd7fd590_1
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libffi=3.4.4=hca03da5_1
  - libsodium=1.0.20=h99b78c6_0
  - libzlib=1.3.1=h5f15de7_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.0=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.2=pyhc872135_1
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.0.0=py311haa24f5a_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.11.14=hf701271_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - pyzmq=27.1.0=py311h5a8c52c_1
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py311hca03da5_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=h79febb2_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.4=py311haa24f5a_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zeromq=4.3.5=h888dc83_9
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - anyio==4.12.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - async-lru==2.0.5
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - contourpy==1.3.3
      - cycler==0.12.1
      - defusedxml==0.7.1
      - fastjsonschema==2.21.2
      - filelock==3.20.0
      - fonttools==4.61.1
      - fqdn==1.5.1
      - fsspec==2025.10.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jinja2==3.1.6
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.5.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - lark==1.3.1
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mistune==3.1.4
      - mouseinfo==0.1.3
      - mpmath==1.3.0
      - mss==10.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.5
      - notebook==7.5.1
      - notebook-shim==0.2.4
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - pillow==12.0.0
      - prometheus-client==0.23.1
      - pyautogui==0.9.54
      - pycparser==2.23
      - pygetwindow==0.0.9
      - pymsgbox==2.0.1
      - pynput==1.8.1
      - pyobjc-core==12.0
      - pyobjc-framework-applicationservices==12.0
      - pyobjc-framework-cocoa==12.0
      - pyobjc-framework-coretext==12.0
      - pyobjc-framework-quartz==12.0
      - pyparsing==3.2.5
      - pyperclip==1.11.0
      - pyrect==0.2.0
      - pyscreeze==1.0.1
      - python-json-logger==4.0.0
      - pytweening==1.2.0
      - pyyaml==6.0.3
      - referencing==0.37.0
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.30.0
      - rubicon-objc==0.5.2
      - send2trash==1.8.3
      - soupsieve==2.8
      - sympy==1.14.0
      - terminado==0.18.1
      - tinycss2==1.4.0
      - torch==2.9.0
      - torchvision==0.24.0
      - tzdata==2025.3
      - uri-template==1.3.0
      - urllib3==2.6.2
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - widgetsnbextension==4.0.15
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/geo-dash-rl
